apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: kubeguardian-demo
  labels:
    app: backend
    app.kubernetes.io/part-of: kubeguardian-demo
type: Opaque
stringData:
  MONGODB_URI: mongodb://admin:changeme-in-production@172.20.237.183:27017/kubeguardian?authSource=admin
