apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: kubeguardian-demo
  labels:
    app: backend
    app.kubernetes.io/part-of: kubeguardian-demo
type: Opaque
stringData:
  MONGODB_URI: mongodb://mongodb:27017/kubeguardian
