apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: kubeguardian-demo
  labels:
    app: mongodb
    app.kubernetes.io/part-of: kubeguardian-demo
data:
  MONGO_INITDB_DATABASE: kubeguardian
