apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: kubeguardian-demo
  labels:
    app: mongodb
    app.kubernetes.io/part-of: kubeguardian-demo
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: changeme-in-production
