apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: kubeguardian-demo
  labels:
    app: mongodb
    app.kubernetes.io/part-of: kubeguardian-demo
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
      name: mongodb
