apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: kubeguardian-demo
  labels:
    app: frontend
    app.kubernetes.io/part-of: kubeguardian-demo
type: Opaque
stringData:
  PLACEHOLDER: "no-secrets-required-for-static-frontend"
